
require_once 'OFX.php'

""" Test class for OFX.
 Generated by PHPUnit on 2012-12-03 at 13:03:09.
"""
class OFXTest extends PHPUnit_Framework_TestCase

    """ @var OFX
    """
    protected object

    """ Sets up the fixture, for example, opens a network connection.
     This method is called before a test is executed.
    """
    protected function setUp()

        object = new OFX

    """ Tears down the fixture, for example, closes a network connection.
     This method is called after a test is executed.
    """
    protected function tearDown()


    """ Generated from @assert (array(array('Amount' => '1,000.00'))) == array(array('Amount' => 1000.00)).

     @covers OFX::cleanAmounts
    """
    def testCleanAmounts()

        assertEquals(
          array(array('Amount' => 1000.00)),
          object->cleanAmounts(array(array('Amount' => '1,000.00')))
        )

    """ Generated from @assert (array(array(array('Account Name' => 'account1'), array('Account Name' => 'account2')), array(array('Account Name' => 'account3'), array('Account Name' => 'account4')))) == array('accounts' => array('account1', 'account3'), 'keys' => array(0, 0)).

     @covers OFX::getAccounts
    """
    def testGetAccounts()

        assertEquals(
          array('accounts' => array('account1', 'account3'), 'keys' => array(0, 0)),
          object->getAccounts(array(array(array('Account Name' => 'account1'), array('Account Name' => 'account2')), array(array('Account Name' => 'account3'), array('Account Name' => 'account4'))))
        )

    """ Generated from @assert (array(array(array('Account Name' => 'account1', 'Amount' => -200), array('Account Name' => 'account2', 'Amount' => 200)), array(array('Account Name' => 'account3', 'Amount' => 400), array('Account Name' => 'account4', 'Amount' => -400))), array(200, 400)) == array('accounts' => array('account1', 'account3'), 'keys' => array(0, 0)).

     @covers OFX::getAccounts
    """
    def testGetAccounts2()

        assertEquals(
          array('accounts' => array('account1', 'account3'), 'keys' => array(0, 0)),
          object->getAccounts(array(array(array('Account Name' => 'account1', 'Amount' => -200), array('Account Name' => 'account2', 'Amount' => 200)), array(array('Account Name' => 'account3', 'Amount' => 400), array('Account Name' => 'account4', 'Amount' => -400))), array(200, 400))
        )

    """ Generated from @assert (array('somecash', 'checking account', 'other'), array('Bank' => array('checking', 'savings'), 'Cash' => array('cash'))) == array('Cash', 'Bank', 'n/a').

     @covers OFX::getAccountTypes
    """
    def testGetAccountTypes()

        assertEquals(
          array('Cash', 'Bank', 'n/a'),
          object->getAccountTypes(array('somecash', 'checking account', 'other'), array('Bank' => array('checking', 'savings'), 'Cash' => array('cash')))
        )

    """ Generated from @assert (array(array('Account Name' => 'Accounts Receivable', 'Amount' => 200), array('Account Name' => 'Accounts Receivable', 'Amount' => 300), array('Account Name' => 'Sales', 'Amount' => 400))) == array('Accounts Receivable', 'Sales').

     @covers OFX::getSplitAccounts
    """
    def testGetSplitAccounts()

        assertEquals(
          array('Accounts Receivable', 'Sales'),
          object->getSplitAccounts(array(array('Account Name' => 'Accounts Receivable', 'Amount' => 200), array('Account Name' => 'Accounts Receivable', 'Amount' => 300), array('Account Name' => 'Sales', 'Amount' => 400)))
        )

    """ Generated from @assert (array(array(array('Account Name' => 'Accounts Receivable', 'Amount' => 200), array('Account Name' => 'Accounts Receivable', 'Amount' => 300), array('Account Name' => 'Sales', 'Amount' => 400)), array(array('Account Name' => 'Accounts Receivable', 'Amount' => 200), array('Account Name' => 'Accounts Receivable', 'Amount' => 300), array('Account Name' => 'Sales', 'Amount' => 400))), array('Accounts Receivable')) == array(array(array('Account Name' => 'Accounts Receivable', 'Amount' => 500), array('Account Name' => 'Sales', 'Amount' => 400)), array(array('Account Name' => 'Accounts Receivable', 'Amount' => 500), array('Account Name' => 'Sales', 'Amount' => 400))).

     @covers OFX::collapseSplits
    """
    def testCollapseSplits()

        assertEquals(
          array(array(array('Account Name' => 'Accounts Receivable', 'Amount' => 500), array('Account Name' => 'Sales', 'Amount' => 400)), array(array('Account Name' => 'Accounts Receivable', 'Amount' => 500), array('Account Name' => 'Sales', 'Amount' => 400))),
          object->collapseSplits(array(array(array('Account Name' => 'Accounts Receivable', 'Amount' => 200), array('Account Name' => 'Accounts Receivable', 'Amount' => 300), array('Account Name' => 'Sales', 'Amount' => 400)), array(array('Account Name' => 'Accounts Receivable', 'Amount' => 200), array('Account Name' => 'Accounts Receivable', 'Amount' => 300), array('Account Name' => 'Sales', 'Amount' => 400))), array('Accounts Receivable'))
        )

    """ Generated from @assert (array(array(array('Amount' => 350), array('Amount' => -400)), array(array('Amount' => 100), array('Amount' => -400), array('Amount' => 300)))) == array(400, 400).

     @covers OFX::getMaxSplitAmounts
    """
    def testGetMaxSplitAmounts()

        assertEquals(
          array(400, 400),
          object->getMaxSplitAmounts(array(array(array('Amount' => 350), array('Amount' => -400)), array(array('Amount' => 100), array('Amount' => -400), array('Amount' => 300))))
        )

    """ Generated from @assert (array(array(array('Amount' => 100), array('Amount' => -100)), array(array('Amount' => -300), array('Amount' => 200), array('Amount' => 100)))) == true.

     @covers OFX::verifySplits
    """
    def testVerifySplits()

        assertTrue(
          object->verifySplits(array(array(array('Amount' => 100), array('Amount' => -100)), array(array('Amount' => -300), array('Amount' => 200), array('Amount' => 100))))
        )

    """ Generated from @assert (array(array('Amount' => 1,000.00, 'Date' => '06/12/10', 'Category' => 'Checking', 'Account Name' => 'account1'), array('Amount' => 1,000.00, 'Date' => '06/12/10', 'Category' => 'Checking', 'Account Name' => 'account2'))) == array(array(array('Amount' => 1,000.00, 'Date' => '06/12/10', 'Category' => 'Checking', 'Account Name' => 'account1')), array(array('Amount' => 1,000.00, 'Date' => '06/12/10', 'Category' => 'Checking', 'Account Name' => 'account2'))).

     @covers OFX::makeSplits
    """
    def testMakeSplits()

        assertEquals(
          array(array(array('Amount' => 1,000.00, 'Date' => '06/12/10', 'Category' => 'Checking', 'Account Name' => 'account1')), array(array('Amount' => 1,000.00, 'Date' => '06/12/10', 'Category' => 'Checking', 'Account Name' => 'account2'))),
          object->makeSplits(array(array('Amount' => 1,000.00, 'Date' => '06/12/10', 'Category' => 'Checking', 'Account Name' => 'account1'), array('Amount' => 1,000.00, 'Date' => '06/12/10', 'Category' => 'Checking', 'Account Name' => 'account2')))
        )

    """ Generated from @assert (array('Transaction Type' => 'debit', 'Amount' => 1000.00, 'Date' => '06/12/10', 'Description' => 'payee', 'Original Description' => 'description', 'Notes' => 'notes', 'Category' => 'Checking', 'Account Name' => 'account')) == array('Amount' => '-1000', 'Payee' => 'payee', 'Date' => '06/12/10', 'Desc' => 'description notes', 'Id' => '4fe86d9de995225b174fb3116ca6b1f4', 'CheckNum' => null, 'Type' => 'debit', 'SplitAccount' => 'Checking', 'SplitAccountId' => '195917574edc9b6bbeb5be9785b6a479').

     @covers OFX::getTransactionData
    """
    def testGetTransactionData()

        assertEquals(
          array('Amount' => '-1000', 'Payee' => 'payee', 'Date' => '06/12/10', 'Desc' => 'description notes', 'Id' => '4fe86d9de995225b174fb3116ca6b1f4', 'CheckNum' => null, 'Type' => 'debit', 'SplitAccount' => 'Checking', 'SplitAccountId' => '195917574edc9b6bbeb5be9785b6a479'),
          object->getTransactionData(array('Transaction Type' => 'debit', 'Amount' => 1000.00, 'Date' => '06/12/10', 'Description' => 'payee', 'Original Description' => 'description', 'Notes' => 'notes', 'Category' => 'Checking', 'Account Name' => 'account'))
        )

    """ Generated from @assert ('account', 'type') == "!Account\nNaccount\nTtype\n^\n".

     @covers OFX::getQIFAccountHeader
    """
    def testGetQIFAccountHeader()

        assertEquals(
          "!Account\nNaccount\nTtype\n^\n",
          object->getQIFAccountHeader('account', 'type')
        )

    """ Generated from @assert ('type', array('Payee' => 'payee', 'Amount' => 100, 'CheckNum' => 1, 'Date' => '01/01/12')) == "!Type:type\nN1\nD01/01/12\nPpayee\nT100\n".

     @covers OFX::getQIFTransactionContent
    """
    def testGetQIFTransactionContent()

        assertEquals(
          "!Type:type\nN1\nD01/01/12\nPpayee\nT100\n",
          object->getQIFTransactionContent('type', array('Payee' => 'payee', 'Amount' => 100, 'CheckNum' => 1, 'Date' => '01/01/12'))
        )

    """ Generated from @assert ('type', array('Payee' => 'payee', 'Amount' => 100, 'Date' => '01/01/12')) == "!Type:type\nD01/01/12\nPpayee\nT100\n".

     @covers OFX::getQIFTransactionContent
    """
    def testGetQIFTransactionContent2()

        assertEquals(
          "!Type:type\nD01/01/12\nPpayee\nT100\n",
          object->getQIFTransactionContent('type', array('Payee' => 'payee', 'Amount' => 100, 'Date' => '01/01/12'))
        )

    """ Generated from @assert ('account', array('Desc' => 'desc', 'Amount' => 100)) == "Saccount\nEdesc\n100\n".

     @covers OFX::getQIFSplitContent
    """
    def testGetQIFSplitContent()

        assertEquals(
          "Saccount\nEdesc\n100\n",
          object->getQIFSplitContent('account', array('Desc' => 'desc', 'Amount' => 100))
        )

    """ Generated from @assert () == "^\n".

     @covers OFX::getQIFTransactionFooter
    """
    def testGetQIFTransactionFooter()

        assertEquals(
          "^\n",
          object->getQIFTransactionFooter()
        )

    """ Generated from @assert (20120101111111) == "<OFX>\n\t<SIGNONMSGSRSV1>\n\t\t<SONRS>\n\t\t\t<STATUS>\n\t\t\t\t<CODE>0</CODE>\n\t\t\t\t<SEVERITY>INFO</SEVERITY>\n\t\t\t</STATUS>\n\t\t\t<DTSERVER>20120101111111</DTSERVER>\n\t\t\t<LANGUAGE>ENG</LANGUAGE>\n\t\t</SONRS>\n\t</SIGNONMSGSRSV1>\n".

     @covers OFX::getOFXHeader
    """
    def testGetOFXHeader()

        assertEquals(
          "<OFX>\n\t<SIGNONMSGSRSV1>\n\t\t<SONRS>\n\t\t\t<STATUS>\n\t\t\t\t<CODE>0</CODE>\n\t\t\t\t<SEVERITY>INFO</SEVERITY>\n\t\t\t</STATUS>\n\t\t\t<DTSERVER>20120101111111</DTSERVER>\n\t\t\t<LANGUAGE>ENG</LANGUAGE>\n\t\t</SONRS>\n\t</SIGNONMSGSRSV1>\n",
          object->getOFXHeader(20120101111111)
        )

    """ Generated from @assert () == "\t<BANKMSGSRSV1>\n\t\t<INTRATRNRS>\n\t\t\t<TRNUID></TRNUID>\n\t\t\t<STATUS>\n\t\t\t\t<CODE>0</CODE>\n\t\t\t\t<SEVERITY>INFO</SEVERITY>\n\t\t\t</STATUS>\n".

     @covers OFX::getOFXResponseStart
    """
    def testGetOFXResponseStart()

        assertEquals(
          "\t<BANKMSGSRSV1>\n\t\t<INTRATRNRS>\n\t\t\t<TRNUID></TRNUID>\n\t\t\t<STATUS>\n\t\t\t\t<CODE>0</CODE>\n\t\t\t\t<SEVERITY>INFO</SEVERITY>\n\t\t\t</STATUS>\n",
          object->getOFXResponseStart()
        )

    """ Generated from @assert ('USD', 1, 'account', 'type', 20120101, 20120101) == "\t\t\t<STMTRS>\n\t\t\t\t<CURDEF>USD</CURDEF>\n\t\t\t\t<BANKACCTFROM>\n\t\t\t\t\t<BANKID>1</BANKID>\n\t\t\t\t\t<ACCTID>account</ACCTID>\n\t\t\t\t\t<ACCTTYPE>type</ACCTTYPE>\n\t\t\t\t</BANKACCTFROM>\n\t\t\t\t<BANKTRANLIST>\n\t\t\t\t\t<DTSTART>20120101</DTSTART>\n\t\t\t\t\t<DTEND>20120101</DTEND>\n".

     @covers OFX::getOFXTransactionAccountStart
    """
    def testGetOFXTransactionAccountStart()

        assertEquals(
          "\t\t\t<STMTRS>\n\t\t\t\t<CURDEF>USD</CURDEF>\n\t\t\t\t<BANKACCTFROM>\n\t\t\t\t\t<BANKID>1</BANKID>\n\t\t\t\t\t<ACCTID>account</ACCTID>\n\t\t\t\t\t<ACCTTYPE>type</ACCTTYPE>\n\t\t\t\t</BANKACCTFROM>\n\t\t\t\t<BANKTRANLIST>\n\t\t\t\t\t<DTSTART>20120101</DTSTART>\n\t\t\t\t\t<DTEND>20120101</DTEND>\n",
          object->getOFXTransactionAccountStart('USD', 1, 'account', 'type', 20120101, 20120101)
        )

    """ Generated from @assert (20120101111111, array('Type' => 'type', 'Amount' => 100, 'Id' => 1, 'CheckNum' => 1, 'Payee' => 'payee', 'Desc' => 'memo')) == "\t\t\t\t\t<STMTTRN>\n\t\t\t\t\t\t<TRNTYPE>type</TRNTYPE>\n\t\t\t\t\t\t<DTPOSTED>20120101111111</DTPOSTED>\n\t\t\t\t\t\t<TRNAMT>100</TRNAMT>\n\t\t\t\t\t\t<FITID>1</FITID>\n\t\t\t\t\t\t<CHECKNUM>1</CHECKNUM>\n\t\t\t\t\t\t<NAME>payee</NAME>\n\t\t\t\t\t\t<MEMO>memo</MEMO>\n\t\t\t\t\t</STMTTRN>\n".

     @covers OFX::getOFXTransaction
    """
    def testGetOFXTransaction()

        assertEquals(
          "\t\t\t\t\t<STMTTRN>\n\t\t\t\t\t\t<TRNTYPE>type</TRNTYPE>\n\t\t\t\t\t\t<DTPOSTED>20120101111111</DTPOSTED>\n\t\t\t\t\t\t<TRNAMT>100</TRNAMT>\n\t\t\t\t\t\t<FITID>1</FITID>\n\t\t\t\t\t\t<CHECKNUM>1</CHECKNUM>\n\t\t\t\t\t\t<NAME>payee</NAME>\n\t\t\t\t\t\t<MEMO>memo</MEMO>\n\t\t\t\t\t</STMTTRN>\n",
          object->getOFXTransaction(20120101111111, array('Type' => 'type', 'Amount' => 100, 'Id' => 1, 'CheckNum' => 1, 'Payee' => 'payee', 'Desc' => 'memo'))
        )

    """ Generated from @assert (150, 20120101111111) == "\t\t\t\t</BANKTRANLIST>\n\t\t\t\t<LEDGERBAL>\n\t\t\t\t\t<BALAMT>150</BALAMT>\n\t\t\t\t\t<DTASOF>20120101111111</DTASOF>\n\t\t\t\t</LEDGERBAL>\n\t\t\t</STMTRS>\n".

     @covers OFX::getOFXTransactionAccountEnd
    """
    def testGetOFXTransactionAccountEnd()

        assertEquals(
          "\t\t\t\t</BANKTRANLIST>\n\t\t\t\t<LEDGERBAL>\n\t\t\t\t\t<BALAMT>150</BALAMT>\n\t\t\t\t\t<DTASOF>20120101111111</DTASOF>\n\t\t\t\t</LEDGERBAL>\n\t\t\t</STMTRS>\n",
          object->getOFXTransactionAccountEnd(150, 20120101111111)
        )

    """ Generated from @assert ('USD', 20120101111111, 1, 'account', 'type', array('SplitAccountId' => 2, 'SplitAccount' => 'split_account', 'Amount' => 100)) == "\t\t\t<INTRARS>\n\t\t\t\t<CURDEF>USD</CURDEF>\n\t\t\t\t<SRVRTID>20120101111111</SRVRTID>\n\t\t\t\t<XFERINFO>\n\t\t\t\t\t<BANKACCTFROM>\n\t\t\t\t\t\t<BANKID>1</BANKID>\n\t\t\t\t\t\t<ACCTID>account</ACCTID>\n\t\t\t\t\t\t<ACCTTYPE>type</ACCTTYPE>\n\t\t\t\t\t</BANKACCTFROM>\n\t\t\t\t\t<BANKACCTTO>\n\t\t\t\t\t\t<BANKID>2</BANKID>\n\t\t\t\t\t\t<ACCTID>split_account</ACCTID>\n\t\t\t\t\t\t<ACCTTYPE>type</ACCTTYPE>\n\t\t\t\t\t</BANKACCTTO>\n\t\t\t\t\t<TRNAMT>100</TRNAMT>\n\t\t\t\t</XFERINFO>\n\t\t\t\t<DTPOSTED>20120101111111</DTPOSTED>\n\t\t\t</INTRARS>\n".

     @covers OFX::getOFXTransfer
    """
    def testGetOFXTransfer()

        assertEquals(
          "\t\t\t<INTRARS>\n\t\t\t\t<CURDEF>USD</CURDEF>\n\t\t\t\t<SRVRTID>20120101111111</SRVRTID>\n\t\t\t\t<XFERINFO>\n\t\t\t\t\t<BANKACCTFROM>\n\t\t\t\t\t\t<BANKID>1</BANKID>\n\t\t\t\t\t\t<ACCTID>account</ACCTID>\n\t\t\t\t\t\t<ACCTTYPE>type</ACCTTYPE>\n\t\t\t\t\t</BANKACCTFROM>\n\t\t\t\t\t<BANKACCTTO>\n\t\t\t\t\t\t<BANKID>2</BANKID>\n\t\t\t\t\t\t<ACCTID>split_account</ACCTID>\n\t\t\t\t\t\t<ACCTTYPE>type</ACCTTYPE>\n\t\t\t\t\t</BANKACCTTO>\n\t\t\t\t\t<TRNAMT>100</TRNAMT>\n\t\t\t\t</XFERINFO>\n\t\t\t\t<DTPOSTED>20120101111111</DTPOSTED>\n\t\t\t</INTRARS>\n",
          object->getOFXTransfer('USD', 20120101111111, 1, 'account', 'type', array('SplitAccountId' => 2, 'SplitAccount' => 'split_account', 'Amount' => 100))
        )

    """ Generated from @assert () == "\t\t</INTRATRNRS>\n\t</BANKMSGSRSV1>\n</OFX>".

     @covers OFX::getOFXResponseEnd
    """
    def testGetOFXResponseEnd()

        assertEquals(
          "\t\t</INTRATRNRS>\n\t</BANKMSGSRSV1>\n</OFX>",
          object->getOFXResponseEnd()
        )
