#!/usr/bin/env python

try:
  # attempt to use the installed python package
  import csv2ofx
except:
  # attempt to run the package from the source directory
  import sys
  sys.path.insert (0,'src')
  import csv2ofx
  

if __name__ == '__main__':
    a=csv2ofx.csv2ofx()
    a.MainLoop()
