<?php

require_once '/Users/reubano/Documents/Projects/csv2ofx/lib_general/Vars.php';

/**
 * Test class for Vars.
 * Generated by PHPUnit on 2012-09-30 at 22:07:04.
 */
class VarsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Vars
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Vars;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert (array('one', '2w', 'GLOBALS' => '3a')) == array('one', '2w').
     *
     * @covers Vars::getVars
     */
    public function testGetVars()
    {
        $this->assertEquals(
          array('one', '2w'),
          $this->object->getVars(array('one', '2w', 'GLOBALS' => '3a'))
        );
    }
}
?>
