
require_once 'File.php'

""" Test class for File.
 Generated by PHPUnit on 2012-12-02 at 17:08:20.
"""
class FileTest extends PHPUnit_Framework_TestCase

    """ @var File
    """
    protected object

    """ Sets up the fixture, for example, opens a network connection.
     This method is called before a test is executed.
    """
    protected function setUp()

        object = new File

    """ Tears down the fixture, for example, closes a network connection.
     This method is called after a test is executed.
    """
    protected function tearDown()


    """ Generated from @assert ('file.ext') == 'ext'.

     @covers File::getExtension
    """
    def testGetExtension()

        assertEquals(
          'ext',
          object->getExtension('file.ext')
        )

    """ Generated from @assert ('/path/to/file.ext') == 'ext'.

     @covers File::getExtension
    """
    def testGetExtension2()

        assertEquals(
          'ext',
          object->getExtension('/path/to/file.ext')
        )

    """ Generated from @assert ('file.ext') == 'file'.

     @covers File::getBase
    """
    def testGetBase()

        assertEquals(
          'file',
          object->getBase('file.ext')
        )

    """ Generated from @assert ('/path/to/file.ext') == 'file'.

     @covers File::getBase
    """
    def testGetBase2()

        assertEquals(
          'file',
          object->getBase('/path/to/file.ext')
        )

    """ @covers File::write2File
     @todo Implement testWrite2File().
    """
    def testWrite2File()

        # Remove the following lines when you implement this test.
        markTestIncomplete(
          'This test has not been implemented yet.'
        )

    """ @covers File::getFullPath
     @todo Implement testGetFullPath().
    """
    def testGetFullPath()

        # Remove the following lines when you implement this test.
        markTestIncomplete(
          'This test has not been implemented yet.'
        )

    """ @covers File::file2Array
     @todo Implement testFile2Array().
    """
    def testFile2Array()

        # Remove the following lines when you implement this test.
        markTestIncomplete(
          'This test has not been implemented yet.'
        )

    """ @covers File::file2String
     @todo Implement testFile2String().
    """
    def testFile2String()

        # Remove the following lines when you implement this test.
        markTestIncomplete(
          'This test has not been implemented yet.'
        )

