
require_once 'Vars.php'

""" Test class for Vars.
 Generated by PHPUnit on 2012-12-02 at 17:08:49.
"""
class VarsTest extends PHPUnit_Framework_TestCase

    """ @var Vars
    """
    protected object

    """ Sets up the fixture, for example, opens a network connection.
     This method is called before a test is executed.
    """
    protected function setUp()

        object = new Vars

    """ Tears down the fixture, for example, closes a network connection.
     This method is called after a test is executed.
    """
    protected function tearDown()


    """ Generated from @assert (array('one', '2w', 'GLOBALS' => '3a')) == array('one', '2w').

     @covers Vars::getVars
    """
    def testGetVars()

        assertEquals(
          array('one', '2w'),
          object->getVars(array('one', '2w', 'GLOBALS' => '3a'))
        )

